$(document).ready(function(){
	$("#top").animate({
		opacity:"0.9",
		top:"10px"
	},2000);
	$("#content").animate({
		opacity:"0.9",
		top:"180px"
	},2000);
	$("#UI").animate({
		opacity:"0.9",
		right:"0px"
	},"slow");
})